# Generated by Django 3.2.4 on 2022-09-09 17:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_videonews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='ndes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sdes',
            field=tinymce.models.HTMLField(),
        ),
    ]
